version: '3.2'

services:

  bookstore:
    build:
      context: ./docker
      args:
        - http_proxy=http://webproxy.frd.shsdir.nl:8080
        - https_proxy=http://webproxy.frd.shsdir.nl:8080
    image: bookstore_custom
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./code/:/code
    ports:
      - 8000:8000
    networks:
      - lab_network

  jupyter:
    image: bookstore_custom
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.password=sha1:58eaa2e688ae:11fd96685b9203d1256a1e09603c9be4f62c94b6
    volumes:
      - ./notebooks/:/code
      - ./code/:/bookstore
      - ./templates/:/templates
      - ./docker-compose.yml:/docker-compose.yml
    ports:
      - 8888:8888
    networks:
      - lab_network

  splunk:
    image: splunk/splunk:latest
    environment:
      - 'SPLUNK_START_ARGS=--accept-license'
      - 'SPLUNK_PASSWORD=secret123'
    ports:
      - 8080:8000
    networks:
      - lab_network

  vault:
    image: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=secret123
      # - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1234
    ports:
      - 8200:8200
    networks:
      - lab_network

  postgres:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret123'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lab_network


volumes:
  pgdata:


networks:
  lab_network:
    external: false
